---
name: CI
on:
    push:
        branches:
            - "**"
        tags-ignore:
            - "**"
jobs:
    unit_test:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Test 1
              run: |
                  echo "TOKEN: $GITHUB_TOKEN"
              env:
                  GITHUB_TOKEN: ${{ secrets.OUR_GITHUB_TOKEN }}

            - name: Test 2
              run: |
                  echo "RUNNING DOCKER:"
                  docker run --env GITHUB_TOKEN=$OUR_GITHUB_TOKEN debian:buster-slim bash -c 'echo "TOKEN: $GITHUB_TOKEN"'
              env:
                  GITHUB_TOKEN: ${{ secrets.OUR_GITHUB_TOKEN }}
